# Generated by Django 5.1.1 on 2024-10-07 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='API',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('service_endpoint', models.CharField(max_length=255)),
                ('group_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apis', to='camera.apigroup')),
            ],
        ),
        migrations.CreateModel(
            name='CameraModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, unique=True)),
                ('api_groups', models.ManyToManyField(related_name='camera_models', to='camera.apigroup')),
            ],
        ),
        migrations.CreateModel(
            name='CameraInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=255, unique=True)),
                ('action_list_url', models.URLField(help_text='URL endpoint for API calls.')),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='camera.cameramodel')),
            ],
        ),
    ]
