# Generated by Django 5.1.1 on 2024-09-21 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CameraInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friendly_name', models.CharField(help_text='Camera model.', max_length=255)),
                ('uuid', models.CharField(help_text='Unique identifier of the camera.', max_length=255, unique=True)),
                ('model', models.CharField(help_text='Device line.', max_length=255)),
                ('action_list_url', models.URLField(help_text='URL endpoint for API calls.')),
            ],
        ),
        migrations.CreateModel(
            name='CameraService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_types', models.TextField(help_text='List of service types.')),
                ('camera_info', models.ForeignKey(help_text='The camera to which the services belong.', on_delete=django.db.models.deletion.CASCADE, related_name='services', to='camera.camerainfo')),
            ],
        ),
    ]
