# Generated by Django 5.1.1 on 2024-10-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='json_params',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
