# Generated by Django 5.1.1 on 2024-10-22 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0002_api_json_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='json_object',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='camerainfo',
            name='last_connected',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
