# Generated by Django 5.1.1 on 2024-10-22 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0003_api_json_object_camerainfo_last_connected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='json_object',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
