# Generated by Django 5.1.1 on 2024-10-22 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0004_alter_api_json_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='json_object',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api',
            name='json_params',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
