# Generated by Django 5.1.1 on 2024-10-22 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0005_alter_api_json_object_alter_api_json_params'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='json_object',
            field=models.TextField(blank=True, null=True),
        ),
    ]
