# Generated by Django 5.1.1 on 2024-10-29 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0009_alter_api_json_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='required_mode',
            field=models.CharField(blank=True, choices=[('record', 'Record mode'), ('stillShoot', 'Still shooting mode'), ('movieShoot', 'Movie shooting mode')], max_length=100, null=True),
        ),
    ]
